spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/identity_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      url: redis://redis:6379
  cache:
    type: redis

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/enterprise-platform

  kafka:
    bootstrap-servers: kafka:9092
