server:
  port: 8080

spring:
  application:
    name: core-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  security:
    cors:
      allowed-origins: "*"